### ISSUE TITLE
make-ca support for openssl 3.0

### ISSUE THREAD

**Issue by satya-rajesh** [lfs-book/make-ca#14]
Hi lucas,

I am raising this issue as i see you are the author of below script:

#!/usr/bin/perl -w
# Used to generate PEM encoded files from Mozilla certdata.txt.
# Run as ./make-cert.pl > certificate.crt
# Parts of this script courtesy of RedHat (mkcabundle.pl)
# This script modified for use with single file data (tempfile.cer) extracted
# from certdata.txt, taken from the latest version in the Mozilla NSS source.
# mozilla/security/nss/lib/ckfw/builtins/certdata.txt
# Authors:  DJ Lucas
#   Bruce Dubbs
# Version 20120211

When i tried this script for openssl 3.0 alpha 13 (i also notice this issue from alpha 8 onwards):

oot [ /usr/src/photon/BUILD ]# perl bin/make-cert.pl > tempfile.crt
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_IN:en",
        LC_ALL = (unset),
        LANG = "en_IN"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Could not read certificate from <stdin>
C021F069927F0000:error:0680008E:asn1 encoding routines:asn1_d2i_read_bio:not enough data:crypto/asn1/a_d2i_fp.c:198:
Unable to load certificate

I see that the input file tempfile.cer has the contents, but somehow the make-cert.pl seems not working with openssl 3.0.0 alpha latest release, it does not generate tempfile.crt.
https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-alpha13

Please note that this script works with 1.1.1 or 1.0.2 openssl without issues.

Any help in this regard is much appreciated.

**Comment by satya-rajesh** [comment]
This needs support for openssl 3.0:
http://www.linuxfromscratch.org/blfs/view/7.10/postlfs/cacerts.html

**Comment by djlucas** [comment]
That script was removed four and a half years ago, and was only ever included here briefly. It may be time to update to a later version of the make-ca script. You can adapt for your existing layout by using the file /etc/make-ca.conf file, but I suspect it'd be much better to rebuild p11-kit and gnutls (and the two or three utilities based on gnutls's single file cacerts) using the new locations.

**Comment by djlucas** [comment]
Actually, scratch that. make-cert.pl was never included in this repo. The initial rewrite was the first commit.

**Comment by satya-rajesh** [comment]
> Actually, scratch that. make-cert.pl was never included in this repo. The initial rewrite was the first commit.

A quick question, is this tested with openssl-3.0 alpha release ?

**Comment by djlucas** [comment]
No, it is not tested. Once we have a beta release (OpenSSL project is running almost exactly a year behind the proposed dates on the wiki, so June??), I'll begin testing. If you'd like to test against the alpha, while my time is limited, please feel free and I'll try to assist in fixing any issues.

**Comment by djlucas** [comment]
No changes are required for OpenSSL-3.0.0.
