### ISSUE TITLE
blanks in get_p11_label

### ISSUE THREAD

**Issue by mijoost** [lfs-book/make-ca#15]
Hi,

I noticed a problem in function get_p11_label() of make-ca (1.7).
This function is (also) used for local x509 certificates.
However, "OpenSSL text values" may have spaces around the '=' in CN, OU, O fields.
This is not properly matched by the regexes in that function, and thus the certificate filename is a generic fallback, rather than based on the label.

Attached please find a patch to correct this problem.

[make-ca-1.7.label1.patch.txt](https://github.com/djlucas/make-ca/files/6824471/make-ca-1.7.label1.patch.txt)

**Comment by djlucas** [comment]
Because of other pending changes, I have a slight preference to normalizing the input as a single string. Of course I can mock one up, but do you happen to have a real world example that is publicly available?

**Comment by mijoost** [comment]
For example, you can (at least in FF) click on github's TLS certificate, save that as PEM format, then:

(see make-ca@658)
>openssl x509 -text -inform PEM -in /tmp/github-com.pem

```Certificate:
    Data:
[...]
       Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = US, O = "DigiCert, Inc.", CN = DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1
        Validity
[...]
```

For whatever reason/circumstances openssl certificates can also occur without those spaces.

Of course, the purpose of the suggested patch is to normalize between those string variants (?!)

**Comment by djlucas** [comment]
Can you see if https://github.com/djlucas/make-ca/commit/bb6015a22402ec8e75df18376d44c9135eb916c2 works for your test case (it should). Note the change to only read from disk once, using Subject instead of issuer (this is important for intermediate CAs), and the use of the last OU value as the first fallback if no CN value. There are a couple more reductions of read from disk coming, as well as a few other minor tweaks laying around in my sandbox, but this should work correctly for your cert. Thanks for bringing it up because I had not caught it previously. Also of interest is the commit before that one for your specific issue as well as all of the ones up to 774b8d9792c8a32be8ccbe2465375c85a04ef19f (breaking up multiple changes).

**Comment by djlucas** [comment]
I'm done adding all of my local changes. What is current will become 1.8 (assuming this also fixes your issue with local certificates in the trust anchors and I don't hear any other issues over the next few days). Note the requirement for p11-kit >= 0.23.19 (added Mozilla's distrust-after dates to the anchors). I've also moved to exporting all of the trusted certificates (not just ca types) in all stores, and followed suit with the distros in naming the anchors (falling short of providing a single p11-kit file as a bundle).

**Comment by mijoost** [comment]
The spaces problem seems resolved now.

Unfortunately there is still a somewhat related problem concerning quotes.
Take said github cert again, and see the O field. This problem isn't limited to the github cert, but occurs on ~20 official root-CA certs as well.

To reproduce, deactivate/comment-out all but the last branch (O=) in get_p11_label()

```
Subject: C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = github.com

Processing local certificates...
Certificate:  "GitHub
Keyhash:      eff031c4
Added to p11-kit anchor directory with trust 'C,,'.
Added to NSS shared DB with trust 'C,,'.

>ls -l /etc/ssl/certs/eff031c4.0
lrwxrwxrwx 1 root root 11 Aug  7 15:22 /etc/ssl/certs/eff031c4.0 -> _GitHub.pem
```
(possible) quotes around any CN/OU/O field should be removed first.
CAVEAT: the quotes likely exist because of the comma inside payload.

**Comment by djlucas** [comment]
Cool. Thanks! It turns out the same is true for OU as well. I haven't found any examples in CN yet, but suppose it is a possibility in the wild. Will commit a fix using '=' as the delimiter as well as some normalization in the next 20 minutes (again, need to separate some changes).

**Comment by djlucas** [comment]
Hopefully fixed permanently in https://github.com/djlucas/make-ca/commit/0ea74dd846e68f4616398832341d2d70604764dd
