### ISSUE TITLE
Is it possible to turn this script into a pure sh script

### ISSUE THREAD

**Issue by XDream8** [lfs-book/make-ca#23]
PS: I want to run this script with a posix compatible shell

**Comment by djlucas** [comment]
Sure, it is possible, but I am unwilling to do so. It's simply a matter of using the correct tool. That said, generally speaking, I do (and did) attempt to limit bashisms. If you really do need to save that tiny bit of space for a bash install (11MB on x86_64 after stripping), or just don't want to pollute your embedded filesystem, it should be perfectly doable. I haven't built a copy of ash (or even dash, which was a fork of the old AST sources IIRC) in many years, but I suspect the only real hairy bash syntax will be the getopt replacement for combined short option handling. Most likely, this could simply be removed, but could be replaced with getopt() if you really want combined short opts - though you'd lose the ability to use long and short options together, which was the reason this was added in the first place. I don't believe there are any expansions/replacements, so just correct the brace syntax (this is not explicitly required for dash), and any double comparators and test it. If you do modify it for sh syntax, please consider creating a pull request. Of course, I'll probably deny it here (unless, of course, you happen to come up with a fully functional getopt() replacement in pure sh), but at least it'll be in the request history and provide a link to your fork if anybody else happens to need the same.
