### ISSUE TITLE
Create symlink pointing to ${CABUNDLE}

### ISSUE THREAD

**Issue by zeckma-tech** [lfs-book/make-ca#28]
This is probably non-standard, but other distros do this, possibly to ensure that Steam can work, which is creating /etc/ssl/certs/ca-certificates.crt which in this case would just be /etc/pki/tls/certs/ca-bundle.crt (${CABUNDLE}). 

This could be accomplished by creating a symlink near or at the end as a finishing step to ensure compatibility. Again, probably not standard, most applications like wget and git do not depend on /etc/ssl/certs/ca-certificates.crt, but Steam does, and for those that wanna go for it, would be a hassle to troubleshoot.

What do you think, would this be a good idea to add?

**Comment by xry111** [comment]
This will be a very bad start of modifying $RANDOM_PACKAGES to support Steam.  AFAIK Steam is still abusing something removed in Glibc-2.36 today - more than one year after Glibc-2.36 release.

No.  We are not going to support non-cooperating closed-source software.

**Comment by djlucas** [comment]
Look, this is a 20 year old plus argument. There is no need to fix Debian's mistake in a downstream package that is not intended for Debian. If you need the symlink for one broken package, then add it. The majority do not and I suspect you do not either. As to troubleshooting, it used to be an FAQ. That said, is this even still an issue? IIUC, it should not be needed nowadays in favor of NSS and the p11-kit symlink for libnssckbi.so. Perhaps we need to look into that but I haven't run Steam in a long time.

--DJ
