### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by viyoriya** [lfs-book/make-ca#5]
in Make file (man: make_ca)
1. man target execute the make_ca and never execute the inside commands and no need to call the make_ca target again its not required.  I just removed the make_ca target from man and added the below line 
2. chmod 755 make-ca.8  
and executed,
Plz test and fix it . Thanks :)

**Comment by djlucas** [comment]
Where did make-ca.8 come from?

**Comment by viyoriya** [comment]
man: make_ca
	chmod 755 help2man
	./help2man -s 8 -N ./make-ca -i include.h2m -o make-ca.8

Got error on this while building linux from scratch and i did this 
man: 
	chmod 755 help2man
	./help2man -s 8 -N ./make-ca -i include.h2m -o make-ca.8
        chmod 755 make-ca.8

Note : I am not a C / C++ developer :) so no idea about make.ca.8 man file...if some one building lfs if they get error on this it will be helpful for them

**Comment by xry111** [comment]
It does not make any sense to set the executable bit on a man page.
